---
- name: Setup of LAMP Stack
  hosts: all
  become: true

  vars:
    php_packages:
      - php
    web_server_packages:
      Ubuntu: apache2
      Amazon: httpd
 

  tasks:
    - name: Install Apache or httpd
      package:
        name: "{{ web_server_packages[ansible_distribution] }}"
        state: present

    - name: Install PHP packages
      package:
        name: "{{ php_packages }}"
        state: present

